<html>
    <head>
        <title>Index of Hydrogen!</title>
        <link href="http://qares.jiuyan.info/201611251416/lib/bootstrap/2.0.0/css/bootstrap.css?t=201611251416" rel="stylesheet" />
        <script src="http://qares.jiuyan.info/201611251416/lib/seajs/1.1.0/sea-jquery.js"></script>
    </head>

    <body>
        <h1>Hello World! <?php echo $this->name; ?>&nbsp;{$name}</h1>
        <span>{$age}</span>
    </body>
</html>

