<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        $t = __DIR__.'/../../../lib/'.str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $class).'.php';
        if (stream_resolve_include_path($t)) {
            require $t;
        }
    },
    true,
    false
);
spl_autoload_register(
    function($class) {
        $t = __DIR__.'/../../../vendor/'.str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $class).'.php';
        if (stream_resolve_include_path($t)) {
            require $t;
        }
    },
    true,
    false
);
//spl_autoload()
// @codeCoverageIgnoreEnd